steps:
  - label: ':docker: build && push staging'
    command: 'ci/login && ci/build && ci/push'
    env:
      DOCKER_PROMOTE_TAG: staging
  - wait
  - label: ':buildkite: upgrade'
    command: 'ci/upgrade'