#!/usr/bin/env bash

run() {
  local dir=$(dirname ${BASH_SOURCE})
  source "${dir}/bash-boilerplate.sh"

  source "${dir}/set-env-vars.sh"

  local image_id="$(docker images | grep -E "^${DOCKER_REPO_NAME} " | tr -s ' ' | cut -d ' ' -f 3)"
  local image_created_timestamp="$(docker inspect -f '{{ .Created }}' ${image_id} | sed -e 's/[:-]//g' | cut -d '.' -f 1)"
  local git_sha="$(git log -1 --pretty=format:"%h")"
  local tag="${DOCKER_SEMVER_MAJOR_MINOR_PATCH_VERSION}-${image_created_timestamp}-${git_sha}-${BUILD_NUMBER}"
  docker tag ${image_id} ${DOCKER_NAMESPACE}/${DOCKER_REPO_NAME}:${tag}
  docker push ${DOCKER_NAMESPACE}/${DOCKER_REPO_NAME}
}

run
